---
- hosts: ansible

  tasks:
  - name: clone repository
    git:
      repo: https://github.com/infomediadesign/sad-01-24-fantasyfootballwebportal.git
      dest: /opt/docker/footballfantasywebportal
      clone: yes
      update: yes

  - name: create gateway service docker image
    command: docker build -t gateway_service -f /opt/docker/footballfantasywebportal/gateway_service/Dockerfile /opt/docker/footballfantasywebportal/gateway_service
    args:
      chdir: /opt/docker/
    register: result

  - debug:
      var: result

  - name: create a tag to push gateway service image into dockerhub
    command: docker tag gateway_service:latest your_docker_hub_username/gateway_service:latest

  - name: push gateway service docker image
    command: docker push your_docker_hub_username/gateway_service:latest

  - name: create match services docker image
    command: docker build -t match_services -f /opt/docker/footballfantasywebportal/match_services/Dockerfile /opt/docker/footballfantasywebportal/match_services
    args:
      chdir: /opt/docker/
    register: result

  - debug:
      var: result

   - name: create a tag to push match services image into dockerhub
    command: docker tag match_services:latest your_docker_hub_username/match_services:latest

  - name: push docker image
    command: docker push your_docker_hub_username/match_services:latest

  - name: create user service docker image
    command: docker build -t user_service -f /opt/docker/footballfantasywebportal/user_service/Dockerfile /opt/docker/footballfantasywebportal/user_service
    args:
      chdir: /opt/docker/
    register: result

  - debug:
      var: result

  - name: create tag to push user service image into dockerhub
    command: docker tag user_service:latest your_docker_hub_username/user_service:latest

  - name: push docker image
    command: docker push your_docker_hub_username/user_service:latest

  - name: create client docker image
    command: docker build -t client -f /opt/docker/footballfantasywebportal/client/Dockerfile /opt/docker/footballfantasywebportal/client
    args:
      chdir: /opt/docker/
    register: result

  - debug:
      var: result

  - name: create tag to push client image into dockerhub
    command: docker tag client:latest your_docker_hub_username/client:latest

  - name: push docker image
    command: docker push your_docker_hub_username/client:latest

  - name: create a micronetwork to run all images as one image.
    command: docker-compose up -d
