apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: footballfantasywebportal
    service: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: footballfantasywebportal
    service: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000

  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: match-services
spec:
  selector:
    app: footballfantasywebportal
    service: match-services
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001

  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: footballfantasywebportal
    service: gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: LoadBalancer
