import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { ReactQuery } from "@/provider/react.query.provider";
import { Toaster } from "react-hot-toast";
import { PermissionCheckContextProvider } from "@/context/permission.check.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-100`}>
        <ReactQuery>
          <PermissionCheckContextProvider>
            <Toaster />
            {children}
          </PermissionCheckContextProvider>
        </ReactQuery>
      </body>
    </html>
  );
}
