import React from "react";
import type { Metadata } from "next";
import { Header } from "@/components/header/header";
export const metadata: Metadata = {
  title: "Control Panel",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header variation={"for-cp"} />
      <main className={"px-[26px]"}>{children}</main>
    </>
  );
}
